openapi: 3.0.3
  info:
    version: 1.0.11
    title: PetStore API
  servers:
    - url: http://localhost:8080
  tags:
    - name: pet
      description: Everything about your Pets
  paths:
    /pet/{petId}/uploadImage:
      post:
        tags:
          - pet
        summary: uploads an image
        description: ''
        operationId: uploadFile
        parameters:
          - name: petId
            in: path
            description: ID of pet to update
            required: true
            schema:
              type: integer
              format: int64
          - name: additionalMetadata
            in: query
            description: Additional Metadata
            required: false
            schema:
              type: string
        requestBody:
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        responses:
          '200':
            description: successful operation
